name: Dependency Submission

on:
  push:
    branches: [ "main", "classic" ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Dependency Submission
        uses: advanced-security/component-detection-dependency-submission-action@v0.1.1
        with:
          # This action will automatically detect the requirements.txt file
          # and submit the dependency graph to GitHub.
          # For Python projects, it uses the pip backend.
          token: ${{ secrets.GITHUB_TOKEN }}
